# This file was generated by GoReleaser. DO NOT EDIT.
cask "hddviz" do
  version "0.3.0"

  on_macos do
    sha256 "20b067a8de3884a2633e36b6eafb49298843bc42ec32be2a177c998e2a688d55"
    url "https://github.com/Toyakki/hddviz/releases/download/v#{version}/hddviz_#{version}_darwin_all.tar.gz"
  end

  name "hddviz"
  desc "CLI tool to simplify HDD usage visualization"
  homepage "https://github.com/Toyakki/hddviz"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hddviz"

  # No zap stanza required

end
