# This file was generated by GoReleaser. DO NOT EDIT.
cask "hddviz" do
  version "0.1.8"

  on_macos do
    url "https://github.com/Toyakki/hddviz/releases/download/v#{version}/hddviz_#{version}_darwin_all.tar.gz"
    sha256 "3aa30493e9c1ac1c0b1798c304ecdd3544c41199c2bc0c767253079a913e41e6"
  end

  name "hddviz"
  desc "CLI tool to simplify HDD usage visualization"
  homepage "https://github.com/Toyakki/hddviz"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hddviz"

  # No zap stanza required

end
