# This file was generated by GoReleaser. DO NOT EDIT.
cask "hddviz" do
  version "0.3.1"

  on_macos do
    sha256 "033b1f86aa070d28abca4204b6318180cd1bb1c1627805e905fc8bc98e793ba5"
    url "https://github.com/Toyakki/hddviz/releases/download/v#{version}/hddviz_#{version}_darwin_all.tar.gz"
  end

  name "hddviz"
  desc "CLI tool to simplify HDD usage visualization"
  homepage "https://github.com/Toyakki/hddviz"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hddviz"

  # No zap stanza required

end
